### ISSUE TITLE
v2/analysis-mongoose-function: Try feature of mongoose in save, find, update, delete, populate, etc and can wrap the idea of mongoose as knowledge that can provide for team to design architecture for restful api

### ISSUE THREAD

**Issue by dangphu2412** [dangphu2412/express-mongoose-boilerplate#5]
- Mongoose have  just integrate create model schema.
- Not support crud as much -> need to deep down to understand how mongoose work with search, save, delete.
- Understand hook in mongoose

**Comment by dangphu2412** [comment]
@quangtudng we will define a formatted input for you to work with then you can start building a mongooseQueryBuilder.
Currently, my idea is the request will be formatted as:
{
    pagination: {
        size:
        offset:
        page:
    },
    sort: [
        {
            key:
            order:
        }, ....
    ],
    filters: [
       {
           key:
           value:
           sign:
       }
    ],
    search: ['id', 'username']
}
Then in your builder when you receive this kind of format will automatically build out the query to reflect the mongoose format. Below is what I have built, which you can refer to.
![image](https://user-images.githubusercontent.com/48615465/113969821-e2d72e00-985f-11eb-94e8-388bde2fc01c.png)

**Comment by quangtudng** [comment]
New commit https://github.com/dangphu2412/express-mongoose-boilerplate/commit/9e93cdfbf121d57c091389827e19c7405d0e94ca
- Updated schema models for 3 modules: **User**, **Role**, **Permission**.
- Updated basic cruds for 3 said modules, including their own controllers, services and routing resolver

**Comment by quangtudng** [comment]
@dangphu2412 Need some reviews for validation process
## Joi Filter module 
Suggestion: Added a second param for the joi filter function so we can dynamically validate in body, param and query
```js
import { BAD_REQUEST } from 'http-status';
import { ERROR_CODE } from '../common/enum';

const joiMappingErrorMessages = e => e.details.map(detail => detail.message);

export const joiFilter = (schema, field) => async (req, res, next) => {
    const validationResult = await schema.validate(req[field]);

    return validationResult.error
        ? res.status(BAD_REQUEST).json({
            status: BAD_REQUEST,
            code: ERROR_CODE.BAD_REQUEST,
            message: joiMappingErrorMessages(validationResult.error)
        })
        : next();
    };
```
## Validation module
Suggestion: Added more function and changed the name of the filter function to utilize it in multiple routes
```js
import Joi from 'joi';
import { joiFilter } from '../../../utils';

class Validator {
    validatePost() {
        const schema = Joi.object({
            email: Joi.string().email({ minDomainSegments: 2, tlds: { allow: ['com', 'net'] } }),
            password: Joi.string().pattern(new RegExp('^[a-zA-Z0-9]{3,30}$')).required(),
            roles: Joi.array().optional(),
        });
        return joiFilter(schema, 'body');
    }

    validateGetAll() {
      //
    }

    validateGetOne() {
      //
    }

    validatePatch() {
      //
    }

    validateDelete() {
      //
    }
}

export const UserValidator = new Validator();
```

**Comment by dangphu2412** [comment]
> @dangphu2412 Need some reviews for the validation process
> 
> ## Joi Filter module
> Suggestion: Added a second param **(field)** for the joi filter function so we can dynamically validate in body, param, and query
> 
> ```js
> import { BAD_REQUEST } from 'http-status';
> import { ERROR_CODE } from '../common/enum';
> 
> const joiMappingErrorMessages = e => e.details.map(detail => detail.message);
> 
> export const joiFilter = (schema, field) => async (req, res, next) => {
>     const validationResult = await schema.validate(req[field]);
> 
>     return validationResult.error
>         ? res.status(BAD_REQUEST).json({
>             status: BAD_REQUEST,
>             code: ERROR_CODE.BAD_REQUEST,
>             message: joiMappingErrorMessages(validationResult.error)
>         })
>         : next();
>     };
> ```
> 
> ## Validation module
> Suggestion: Added more functions and changed the name of the filter function to utilize it in multiple routes
> 
> ```js
> import Joi from 'joi';
> import { joiFilter } from '../../../utils';
> 
> class Validator {
>     validatePost() {
>         const schema = Joi.object({
>             email: Joi.string().email({ minDomainSegments: 2, tlds: { allow: ['com', 'net'] } }),
>             password: Joi.string().pattern(new RegExp('^[a-zA-Z0-9]{3,30}$')).required(),
>             roles: Joi.array().optional(),
>         });
>         return joiFilter(schema, 'body');
>     }
> 
>     validateGetAll() {
>       //
>     }
> 
>     validateGetOne() {
>       //
>     }
> 
>     validatePatch() {
>       //
>     }
> 
>     validateDelete() {
>       //
>     }
> }
> 
> export const UserValidator = new Validator();
> ```

- First point:
   - Is that work well with query and params in expressJs.
   - Hmm I'm now considering between expressValidator and Joi
- Second point:
   - That would be great for our code convention, but we should consider naming detail convention.
