### ISSUE TITLE
v2/auth-model: An authenticate and authorization model.

### ISSUE THREAD

**Issue by dangphu2412** [dangphu2412/express-mongoose-boilerplate#7]
- Design UserDetail
- Design authen model
- Design autho model

**Comment by dangphu2412** [comment]
@ichhoa129 @Jayjaynoplays
![image](https://user-images.githubusercontent.com/48615465/113763834-5ab03600-9744-11eb-8764-bb25b05f2083.png)
Currently, I have drawn some basic systems of authentication and authorization which still not including the detail of implementation.

**Comment by dangphu2412** [comment]
![image](https://user-images.githubusercontent.com/48615465/113845167-6987fe80-97bf-11eb-82d5-76a03c1dddd2.png)
@ichhoa129 @Jayjaynoplays 

- Package folder structure may like this.
- We will develop a class AuthModel (authenticate model) that have some requirement before integrate into a model:
   * Jwt service that helps decode and sign token [link](https://www.npmjs.com/package/jsonwebtoken).
   * Class UserDetail that will contain fields as I mention above. This UserDetail will be passed into the request context of expressJS with the key **AuthContext** exp: req['AuthContext'] -> so that in the controller we may retrieve user detail from request with one function.

**Comment by dangphu2412** [comment]
Implementation:
- @ichhoa129 will responsible for class UserDetail.
- @Jayjaynoplays will responsible for JwtService.
 !note: Just ask me whenever you need some instructions.

**Comment by Jayjaynoplays** [comment]
why we have to use the bcryptjs package instead of bcrypt package
![image](https://user-images.githubusercontent.com/48757266/113999275-16c44a80-9884-11eb-9b04-ad3064f9c84b.png)

**Comment by dangphu2412** [comment]
> why we have to use the bcryptjs package instead of bcrypt package
> ![image](https://user-images.githubusercontent.com/48757266/113999275-16c44a80-9884-11eb-9b04-ad3064f9c84b.png)

Of course it faster than the other one. In the past, when I deploy to the server that bcrypt crash my app and I don't have time to figure it out so I change to use bcryptjs. So you can use bcrypt instead but some remind that you may face my old problem when deploying.

**Comment by dangphu2412** [comment]
@ichhoa129 @Jayjaynoplays @hovanvydut 
![image](https://user-images.githubusercontent.com/48615465/114380890-c109de00-9bb4-11eb-98b8-f7724f86500e.png)
Here is the authorization model:
- We need to integrate PreAuthorize into the handler, validate that req['AuthContext'] is persisted in req or else we will throw UnAuthorizedException()
- We need a function to extract user details from req
- We need an authorization model (which contains rules that need to be registered by a set of rules). Then we can manually add rules by method addRule() of AuthorizationModel then push each rule into a queue then validate() is triggered that will execute command one by one. Any fail will stop the execution and throw ForbiddenException.
- We can call the method of class via string literal, but we need to register all of the class singleton into a place that AuthoModel can collect and execute.
